"""Stage 4: training-ready export.

Joins the audio + quality + review manifests and writes the result as
a self-contained HuggingFace `datasets` folder. The WAVs are copied
into <dataset_dir>/audio/ so the output ships as one portable artifact,
no path rewriting needed by the downstream loader.

We also drop a metadata.jsonl next to it for human inspection, plus
an auto-generated dataset card.

Layout:
    data/final/
        egyptian_arabic_synthetic_v1/
            data-00000-of-00001.arrow
            dataset_info.json
            state.json
            audio/<id>.wav
        metadata.jsonl
        README.md
"""
from __future__ import annotations

import shutil
from collections import Counter
from pathlib import Path
from typing import Any

from datasets import Dataset, Features, Value

from .config import load_config
from .utils import read_jsonl, setup_logging, write_jsonl

log = setup_logging()


def _join_records(cfg: dict[str, Any]) -> list[dict[str, Any]]:
    """Join audio + quality + review manifests by sample id, applying
    the include_rejected / include_flagged filters.
    """
    paths = cfg["paths"]
    ecfg = cfg["export"]
    project_root = Path(cfg["_root"])

    audio = {r["id"]: r for r in read_jsonl(paths["audio_manifest"]) if r.get("status") == "ok"}
    quality = {r["id"]: r for r in read_jsonl(paths["quality_manifest"])}
    reviews = {r["id"]: r for r in read_jsonl(paths["reviewed_manifest"])}  # latest entry wins

    rows: list[dict[str, Any]] = []
    skipped = Counter()

    for sid, a in audio.items():
        rev = reviews.get(sid)
        q = quality.get(sid, {})

        if rev is None:
            skipped["unreviewed"] += 1
            continue
        decision = rev["decision"]
        if decision == "reject" and not ecfg["include_rejected"]:
            skipped["rejected"] += 1
            continue
        # `include_flagged` is conservative: when False (default), drop
        # auto-flagged samples that the human merely 'accepted' as-is.
        # Edits are kept regardless because the human revised the text.
        # Rejected samples were already handled above; if include_rejected
        # is True, an explicit user choice overrides the flag gate.
        is_flagged = q.get("auto_status") == "flagged"
        if (
            is_flagged
            and not ecfg["include_flagged"]
            and decision == "accept"
        ):
            skipped["flagged_accept_only"] += 1
            continue

        # Final transcription: edited text if reviewer corrected it,
        # otherwise the original prompt.
        final_text = rev.get("final_text") or a["text"]

        rows.append({
            "id": sid,
            # Will be rewritten by export_dataset() to a path relative
            # to the dataset directory after the WAV is copied in.
            "audio_relpath": a["audio_path"],
            "text": final_text,
            "original_prompt": a["text"],
            "category": a.get("category"),
            "voice_provider": a["voice_provider"],
            "voice_id": a["voice_id"],
            "voice_gender": a["voice_gender"],
            "voice_dialect": a["voice_dialect"],
            "duration_sec": a.get("duration_sec"),
            "sample_rate": a["sample_rate"],
            "asr_transcript": q.get("transcript"),
            "asr_cer": q.get("cer"),
            "asr_wer": q.get("wer"),
            "auto_flags": q.get("flags", []),
            "auto_status": q.get("auto_status"),
            "review_decision": decision,
            "review_note": rev.get("note"),
            "is_synthetic": True,
            "language": "ar-EG",
        })

    log.info("Joined %d rows; skipped %s", len(rows), dict(skipped))
    return rows


def _write_dataset_card(target_dir: Path, rows: list[dict[str, Any]], cfg: dict[str, Any]) -> None:
    by_voice = Counter(r["voice_id"] for r in rows)
    by_cat = Counter(r["category"] for r in rows)
    total_dur = sum((r.get("duration_sec") or 0.0) for r in rows)
    avg_cer = (sum((r.get("asr_cer") or 0) for r in rows if r.get("asr_cer") is not None)
               / max(1, sum(1 for r in rows if r.get("asr_cer") is not None)))

    lines = [
        "# Egyptian Arabic Synthetic Speech Dataset (v1)",
        "",
        "**Generated by**: SSDP pipeline. **Synthetic**: yes.",
        "**Language tag**: ar-EG (Egyptian Arabic).",
        "",
        f"- Samples: **{len(rows)}**",
        f"- Total duration: **{total_dur / 60:.1f} min** ({total_dur:.0f} s)",
        f"- Average round-trip ASR CER: **{avg_cer:.3f}**",
        f"- Sample rate: **{cfg['tts']['output_sample_rate']} Hz**, mono PCM_16 WAV",
        "",
        "## Voice distribution",
        *[f"- `{v}`: {n}" for v, n in by_voice.most_common()],
        "",
        "## Category distribution",
        *[f"- `{c}`: {n}" for c, n in by_cat.most_common()],
        "",
        "## Schema",
        "- `audio` - string path **relative to this dataset directory** (e.g. `audio/<id>.wav`). Cast to `Audio()` at load time - see usage snippet below.",
        "- `audio_relpath` - string path relative to the source repo root (kept for cross-referencing with `data/audio/`).",
        "- `text` - final reference transcript (post-review).",
        "- `original_prompt` - text fed to the TTS.",
        "- `category` - prompt category (daily_conversation, code_switching, ...).",
        "- `voice_*` - TTS voice metadata.",
        "- `asr_*` - round-trip Whisper transcript and CER/WER.",
        "- `auto_flags`, `auto_status` - automated quality signals.",
        "- `review_decision` - human reviewer's call (accept / edit / reject).",
        "",
        "## Usage",
        "```python",
        "from pathlib import Path",
        "from datasets import load_from_disk, Audio",
        "",
        "ds_path = 'data/final/egyptian_arabic_synthetic_v1'",
        "ds = load_from_disk(ds_path)",
        "# Resolve dataset-relative paths to absolute, then cast.",
        "ds = ds.map(lambda r: {'audio': str(Path(ds_path) / r['audio'])})",
        "ds = ds.cast_column('audio', Audio(sampling_rate=16000))",
        "print(ds[0]['audio']['array'].shape, ds[0]['text'])",
        "```",
        "",
        "## Caveats",
        "- 100% synthetic. Models trained only on this will overfit to the",
        "  TTS voices' acoustic fingerprint and prosody. Mix with real",
        "  Egyptian Arabic data before fine-tuning.",
        "- Egyptian-Arabic dialect is approximated by edge-tts (Salma /",
        "  Shakir voices). gTTS 'ar' is MSA-leaning and is included as a",
        "  contrast voice for diversity.",
        "- Code-switched English words are synthesized inconsistently.",
        "  Inspect `auto_flags == 'high_cer'` clips for examples.",
    ]
    (target_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


def export_dataset(config_path: str | None = None) -> Path:
    cfg = load_config(config_path)
    paths = cfg["paths"]
    ecfg = cfg["export"]
    project_root = Path(cfg["_root"])

    rows = _join_records(cfg)
    if not rows:
        raise RuntimeError(
            "No rows to export. Did you review any samples? "
            "(Check data/reviewed/reviewed.jsonl)"
        )

    final_dir = Path(paths["final_dir"]) / ecfg["dataset_name"]
    final_dir.mkdir(parents=True, exist_ok=True)

    # Always write metadata.jsonl - cheap and trivially inspectable.
    # Keep `audio_relpath` as a repo-root-relative path here for human
    # readability; the HF dataset gets a different, dataset-relative
    # path written below.
    metadata_path = Path(paths["final_dir"]) / "metadata.jsonl"
    write_jsonl(metadata_path, rows)
    log.info("Wrote metadata: %s (%d rows)", metadata_path, len(rows))

    if ecfg["format"] == "jsonl_only":
        log.info("export.format=jsonl_only - skipping HF dataset build.")
        _write_dataset_card(Path(paths["final_dir"]), rows, cfg)
        return Path(paths["final_dir"])

    # Make the HF dataset SELF-CONTAINED: copy each WAV into
    # <final_dir>/audio/<id>.wav so the dataset folder is a single
    # portable artifact. The `audio` column then holds a path RELATIVE
    # TO THE DATASET DIRECTORY, which a downstream loader resolves via:
    #
    #     ds_path = "data/final/egyptian_arabic_synthetic_v1"
    #     ds = load_from_disk(ds_path)
    #     ds = ds.map(lambda r: {"audio": str(Path(ds_path) / r["audio"])})
    #     ds = ds.cast_column("audio", Audio(sampling_rate=16000))
    #
    # We do NOT bake torchcodec-encoded audio bytes at write time
    # because that would force this pipeline to depend on torch /
    # torchcodec - those belong in the training environment.
    audio_subdir = final_dir / "audio"
    audio_subdir.mkdir(parents=True, exist_ok=True)

    ds_rows = []
    for r in rows:
        src = project_root / r["audio_relpath"]
        dst = audio_subdir / src.name
        if not dst.exists():
            shutil.copy2(src, dst)
        d = dict(r)
        d["audio"] = f"audio/{src.name}"            # relative to the dataset dir
        ds_rows.append(d)
    log.info("Copied %d WAVs into %s", len(ds_rows), audio_subdir)

    features = Features({
        "id": Value("string"),
        "audio": Value("string"),                 # path relative to the dataset dir
        "audio_relpath": Value("string"),         # path relative to repo root (for cross-referencing)
        "text": Value("string"),
        "original_prompt": Value("string"),
        "category": Value("string"),
        "voice_provider": Value("string"),
        "voice_id": Value("string"),
        "voice_gender": Value("string"),
        "voice_dialect": Value("string"),
        "duration_sec": Value("float32"),
        "sample_rate": Value("int32"),
        "asr_transcript": Value("string"),
        "asr_cer": Value("float32"),
        "asr_wer": Value("float32"),
        "auto_flags": [Value("string")],
        "auto_status": Value("string"),
        "review_decision": Value("string"),
        "review_note": Value("string"),
        "is_synthetic": Value("bool"),
        "language": Value("string"),
    })

    ds = Dataset.from_list(ds_rows, features=features)
    ds.save_to_disk(str(final_dir))
    log.info("Wrote HF dataset to %s", final_dir)

    _write_dataset_card(Path(paths["final_dir"]), rows, cfg)
    log.info("Export complete. %d samples in %s", len(rows), final_dir)
    return final_dir


if __name__ == "__main__":
    export_dataset()
